version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /home/tgerardi/data/nginx:/etc/nginx/conf.d
      - /home/tgerardi/data/wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - /home/tgerardi/data/wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - /home/tgerardi/data/mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge
